In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Read File
file_path = 'cleaned.csv'
hmda = pd.read_csv(file_path)

In [4]:
hmda_sample = hmda.sample(frac =.10)

In [7]:
len(hmda_sample)

2486666

In [9]:
hmda_sample.dtypes

as_of_year                          int64
action_taken                        int64
loan_type                           int64
loan_purpose                        int64
loan_amount_000s                  float64
msamd                             float64
state_code                        float64
county_code                       float64
applicant_ethnicity                 int64
co_applicant_ethnicity              int64
applicant_race_1                    int64
co_applicant_race_1                 int64
applicant_sex                       int64
co_applicant_sex                    int64
applicant_income_000s             float64
purchaser_type                      int64
rate_spread                       float64
hoepa_status                        int64
population                        float64
minority_population               float64
hud_median_family_income          float64
tract_to_msamd_income             float64
number_of_owner_occupied_units    float64
number_of_1_to_4_family_units     float64
dtype: object

In [11]:
# Dropping rate_spread for now as well
X = hmda_sample.drop(columns=['action_taken', 'rate_spread'])
y = hmda_sample['action_taken']

In [13]:
X = pd.get_dummies(X, drop_first=True)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
# Random Forest Model
rf_model = RandomForestClassifier(random_state=42, verbose=2)
rf_model.fit(X_train, y_train)

building tree 1 of 100
building tree 2 of 100
building tree 3 of 100

KeyboardInterrupt

In [21]:
# Accuracy Scores and Confusion Matrix
from sklearn.metrics import classification_report, confusion_matrix

y_pred = rf_model.predict(X_test)
print(classification_report(y_test, y_pred))
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

KeyboardInterrupt

In [ ]:
# ROC AUC Curve
from sklearn.metrics import roc_curve, auc

fpr, tpr, _ = roc_curve(y_test, rf_model.predict_proba(X_test)[:, 1])
auc_score = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f'AUC = {auc_score:.2f}')
plt.plot([0, 1], [0, 1], linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
importances = rf_model.feature_importances_
features = X.columns
plt.barh(features, importances)
plt.xlabel("Feature Importance")
plt.title("Random Forest Feature Importance")
plt.show()

In [25]:
from sklearn.naive_bayes import GaussianNB

In [26]:
hmda_nb = GaussianNB()

hmda_nb.fit(X_train, y_train)

GaussianNB()

In [28]:
y_pred = hmda_nb.predict(X_test)
print(classification_report(y_test, y_pred))
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95    413621
           1       1.00      0.53      0.69     83713

    accuracy                           0.92    497334
   macro avg       0.95      0.77      0.82    497334
weighted avg       0.93      0.92      0.91    497334

Confusion Matrix
[[413403    218]
 [ 39169  44544]]

In [31]:
y_pred = hmda_nb.predict(X_test)

from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 92.0803725464175

In [33]:
# race_mapping = {5: 'White', 3: 'Black or African American', 2: 'Asian', 1: 'American Indian or Alaska Native', 4: 'Native Hawaiian or Other Pacific Islander'}
# hmda_sample['action_taken'] = hmda_sample['action_taken'].apply(lambda x: 1 if x in [1, 2] else 0)
# hmda_sample['applicant_race_1'] = hmda_sample['applicant_race_1'].map(race_mapping)
# hmda_sample.describe()

In [35]:
hmda_sample['applicant_race_1']

20493630    5
785654      5
23721266    5
11834421    3
5852959     1
           ..
15768785    3
10510466    5
18606040    5
23705045    5
23385277    5
Name: applicant_race_1, Length: 2486666, dtype: int64

In [37]:
#Training the data on white data and then testing on all data
# 5 is white
white_data = hmda_sample[hmda_sample['applicant_race_1'] == 5]
X_white = white_data.drop(columns=['action_taken', 'rate_spread'])
y_white = white_data['action_taken']

In [39]:
white_data

,as_of_year,action_taken,loan_type,loan_purpose,loan_amount_000s,msamd,state_code,county_code,applicant_ethnicity,co_applicant_ethnicity,...,applicant_income_000s,purchaser_type,rate_spread,hoepa_status,population,minority_population,hud_median_family_income,tract_to_msamd_income,number_of_owner_occupied_units,number_of_1_to_4_family_units
20493630,2015,0,2,3,118.0,43900.0,45.0,83.0,1,0,...,45.0,0,-1.00,2,7920.0,16.290001,54800.0,119.900002,2317.0,3005.0
785654,2007,0,1,1,34.0,31084.0,6.0,37.0,2,2,...,371.0,0,-1.00,2,4268.0,35.259998,56500.0,154.720001,1353.0,1538.0
23721266,2017,0,2,1,209.0,38060.0,4.0,13.0,2,0,...,70.0,0,-1.00,2,7333.0,30.400000,66200.0,130.979996,1982.0,3416.0
15220120,2012,0,2,1,181.0,24020.0,36.0,113.0,2,0,...,50.0,0,-1.00,2,3731.0,5.010000,62600.0,99.370003,1068.0,1750.0
9401259,2009,0,1,3,328.0,17140.0,39.0,165.0,2,2,...,149.0,0,-1.00,2,7708.0,6.330000,69200.0,155.580002,2250.0,2500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075418,2007,0,1,3,164.0,18140.0,39.0,159.0,2,0,...,46.0,0,-1.00,2,5738.0,1.850000,64200.0,113.629997,1763.0,2131.0
10510466,2010,0,3,3,305.0,17820.0,8.0,41.0,2,2,...,98.0,0,-1.00,2,4485.0,12.910000,70600.0,154.130005,1261.0,1577.0
18606040,2014,1,2,1,132.0,41420.0,41.0,47.0,1,0,...,31.0,7,1.57,2,4834.0,52.849998,55800.0,105.480003,1012.0,1305.0
23705045,2017,0,1,3,42.0,19124.0,48.0,85.0,2,2,...,112.0,0,-1.00,2,17773.0,33.750000,73400.0,165.919998,4815.0,5128.0
23385277,2017,0,1,3,108.0,23420.0,6.0,19.0,2,0,...,32.0,0,-1.00,2,4372.0,92.379997,50000.0,54.410000,592.0,1238.0

In [40]:
white_data['applicant_race_1']

20493630    5
785654      5
23721266    5
15220120    5
9401259     5
           ..
1075418     5
10510466    5
18606040    5
23705045    5
23385277    5
Name: applicant_race_1, Length: 1959501, dtype: int64

In [43]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_white_scaled = scaler.fit_transform(X_white)

In [44]:
hmda_nb.fit(X_white_scaled, y_white)

GaussianNB()

In [46]:
# Set up data for machine learning
# Create function that creates stratified samples of a dataset
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
def stratified_sample(df, col, sample_size):
    """Creates a new dataframe that has the same proportions of specified column as the original dataframe"""
    sample = pd.DataFrame()
    total_obs = df.shape[0]
    grouped = df.groupby(col)
    for category in list(grouped.groups.keys()):
        group = grouped.get_group(category)
        group_size = group.shape[0]
        group_sample_size = round((group_size / total_obs) * sample_size)
        if sample.shape[0] > 0:
            sample = pd.concat([sample, group.sample(n=group_sample_size, random_state=313)], ignore_index=True)
        else:
            sample = grouped.get_group(category).sample(n=group_sample_size, random_state=313)
    return sample

# Function that collects all data for a specific year
def set_year(df, year):
    """Creates a new dataframe that contains all observations for a specific year"""
    year_data = df[df['as_of_year'] == year]
    return year_data

# Function that splits data into training and test sets
def split_xy(df, y_col):
    """Splits a dataframe into X and y components. The function assumes that the last column is the y variable."""
    X = df.drop(columns=[y_col])
    y = df[y_col]
    return [X, y]

# Create sample function that only draws from specified values in a column
def value_sample(df, col, value, sample_size):
    """Creates a dataframe that has a randome sample of observations that have specified value in
    specified column. For example, if col = 'applicant_race_1' and value = 5 (which corresponds to white), 
    the sample will only have observations where the applicant is white.""" 
    sample = df[df[col] == value].sample(sample_size, random_state=313)
    return sample

# Function that create training data for white model and all race model, and test data for each race
def model_samples(df, year_sample_size, test_sample_size, remove_race=True):
    """Fucntion that creates our training and test data for our ML models. If remove_race is true, the models will be 
    blind to the races of each application."""
    # First collect equal sized samples from each year
    data_by_year = []
    for year in range(2007, 2018):
        year_dataset = set_year(df, year)
        # Create training data for white and all race models
        white_train = value_sample(year_dataset, 'applicant_race_1', 5, year_sample_size)
        all_train = stratified_sample(year_dataset, 'applicant_race_1', year_sample_size)
        if remove_race:
            white_train = white_train.drop(columns=['applicant_race_1', 'co_applicant_race_1'])
            all_train = all_train.drop(columns=['applicant_race_1', 'co_applicant_race_1'])
        # Create test data for each race
        race_tests = []
        for race in range(1, 6):
            race_sample = value_sample(year_dataset, 'applicant_race_1', race, test_sample_size)
            if remove_race:
                race_sample = race_sample.drop(columns=['applicant_race_1', 'co_applicant_race_1'])
            race_tests.append(race_sample)
        data_by_year.append([white_train, all_train, race_tests])
    # Complied the data for each year
    year_data = data_by_year.pop(0) 
    compiled_white = year_data[0]
    compiled_all_race = year_data[1]
    compiled_race_tests = year_data[2]  
    while len(data_by_year) > 0:
        year_data = data_by_year.pop(0)
        compiled_white = pd.concat([compiled_white, year_data[0]], ignore_index=True)
        compiled_all_race = pd.concat([compiled_all_race, year_data[1]], ignore_index=True)
        for i in range(0, 5):
            compiled_race_tests[i] = pd.concat([compiled_race_tests[i], year_data[2][i]], ignore_index=True)
    return [compiled_white, compiled_all_race, compiled_race_tests]

def model_testing(model, sample_data, y_col, cv=5, param_grid=None):
    """Fits white model and all race based on the specified training data. The y_col is the y variable column name.
    The sample_data parameter is the output of the model_samples function and param_grid is the hyperparameter grid
    that will be used in the GridSearchCV function. This function will return the results of the each model with given 
    parameters and the testing results from each race."""
    # Create the white model dataset
    X_white, y_white = split_xy(sample_data[0], y_col)
    # Create the all race model dataset
    X_all, y_all = split_xy(sample_data[1], y_col)

    # Set up Stratified K-Fold cross-validation
    stratified_kfold = StratifiedKFold(n_splits=cv, shuffle=True, random_state=313)
    # Define scoring metrics
    scoring = {'roc_auc': 'roc_auc', 'precision': 'precision', 'recall': 'recall', 'accuracy': 'accuracy'}

    # Initialize GridSearchCV for White Only Model
    white_search = GridSearchCV(model, param_grid, scoring=scoring, cv=stratified_kfold, refit='roc_auc', return_train_score=True)
    white_search.fit(X_white, y_white)
    # Initialize GridSearchCV for All Races Model
    all_search = GridSearchCV(model, param_grid, scoring=scoring, cv=stratified_kfold, refit='roc_auc', return_train_score=True)
    all_search.fit(X_all, y_all)

    # Extract results for each model
    white_results = pd.DataFrame(white_search.cv_results_)
    all_results = pd.DataFrame(all_search.cv_results_)
    # Add model type to results
    white_results['Model'] = 'White only'
    all_results['Model'] = 'All races'
    # Combine results
    combined_results = pd.concat([white_results, all_results])

    # Sort combined results by index then drop
    combined_results = combined_results.sort_index()

    # Select relevant columns and rename them for clarity
    relevant_columns = [f'param_{param}' for param in param_grid.keys()] + [
        'mean_test_roc_auc', 'mean_test_precision', 'mean_test_recall', 'mean_test_accuracy', 'Model']
    combined_results = combined_results[relevant_columns]

    # Rename columns for final output
    column_mapping = {f'param_{param}': param for param in param_grid.keys()}
    column_mapping.update({
        'mean_test_roc_auc': 'ROC-AUC Score',
        'mean_test_precision': 'Precision',
        'mean_test_recall': 'Recall',
        'mean_test_accuracy': 'Accuracy'})
    combined_results.rename(columns=column_mapping, inplace=True)

    # Order the columns of so that Model is first
    column_order = ['Model'] + [param for param in param_grid.keys()] + ['ROC-AUC Score', 'Precision', 'Recall', 'Accuracy']
    combined_results = combined_results[column_order]

    return combined_results

# Remove rate spread from the dataset
hmda_no_rate_spread = hmda_sample.drop(columns=['rate_spread'])

# Adjust sample and test sizes for models and testing 
samples = model_samples(hmda_no_rate_spread, 1000, 200)

# Set up model and hyperparameter grids
logit = LogisticRegression(random_state=313)
rforest = RandomForestClassifier(random_state=313)

model_testing(rforest, samples, 'action_taken', param_grid={'max_depth': [3, 5], 'bootstrap': [True], 'max_samples':[100, 500]}, cv=5)

,Model,max_depth,bootstrap,max_samples,ROC-AUC Score,Precision,Recall,Accuracy
0,White only,3,True,100,0.864321,1.0,0.441509,0.906636
0,All races,3,True,100,0.866177,1.0,0.466737,0.916204
1,White only,3,True,500,0.873952,1.0,0.550829,0.924909
1,All races,3,True,500,0.880286,1.0,0.567399,0.932019
2,White only,5,True,100,0.865381,1.0,0.486669,0.914182
2,All races,5,True,100,0.867990,1.0,0.498561,0.921203
3,White only,5,True,500,0.882910,1.0,0.557908,0.926091
3,All races,5,True,500,0.890341,1.0,0.572601,0.932837

In [353]:
state_mapping = {
    1: 'Alabama', 2: 'Alaska', 4: 'Arizona', 5: 'Arkansas', 6: 'California', 8: 'Colorado', 
    9: 'Connecticut', 10: 'Delaware', 11: 'District of Columbia', 12: 'Florida', 13: 'Georgia', 
    15: 'Hawaii', 16: 'Idaho', 17: 'Illinois', 18: 'Indiana', 19: 'Iowa', 20: 'Kansas', 
    21: 'Kentucky', 22: 'Louisiana', 23: 'Maine', 24: 'Maryland', 25: 'Massachusetts', 
    26: 'Michigan', 27: 'Minnesota', 28: 'Mississippi', 29: 'Missouri', 30: 'Montana', 
    31: 'Nebraska', 32: 'Nevada', 33: 'New Hampshire', 34: 'New Jersey', 35: 'New Mexico', 
    36: 'New York', 37: 'North Carolina', 38: 'North Dakota', 39: 'Ohio', 40: 'Oklahoma', 
    41: 'Oregon', 42: 'Pennsylvania', 44: 'Rhode Island', 45.0: 'South Carolina', 46: 'South Dakota', 
    47: 'Tennessee', 48: 'Texas', 49: 'Utah', 50: 'Vermont', 51: 'Virginia', 53: 'Washington', 
    54: 'West Virginia', 55: 'Wisconsin', 56: 'Wyoming'
}

In [389]:
state_mapping_reversed = {
    'Alabama': 1, 'Alaska': 2, 'Arizona': 4, 'Arkansas': 5, 'California': 6, 'Colorado': 8,
    'Connecticut': 9, 'Delaware': 10, 'District of Columbia': 11, 'Florida': 12, 'Georgia': 13,
    'Hawaii': 15, 'Idaho': 16, 'Illinois': 17, 'Indiana': 18, 'Iowa': 19, 'Kansas': 20,
    'Kentucky': 21, 'Louisiana': 22, 'Maine': 23, 'Maryland': 24, 'Massachusetts': 25,
    'Michigan': 26, 'Minnesota': 27, 'Mississippi': 28, 'Missouri': 29, 'Montana': 30,
    'Nebraska': 31, 'Nevada': 32, 'New Hampshire': 33, 'New Jersey': 34, 'New Mexico': 35,
    'New York': 36, 'North Carolina': 37, 'North Dakota': 38, 'Ohio': 39, 'Oklahoma': 40,
    'Oregon': 41, 'Pennsylvania': 42, 'Rhode Island': 44, 'South Carolina': 45.0, 'South Dakota': 46,
    'Tennessee': 47, 'Texas': 48, 'Utah': 49, 'Vermont': 50, 'Virginia': 51, 'Washington': 53,
    'West Virginia': 54, 'Wisconsin': 55, 'Wyoming': 56
}

In [392]:
hmda_sample['state_code'] = hmda_sample['state_code'].map(state_mapping_reversed)

In [397]:
hmda_sample['state_code']

20493630    45.0
785654       6.0
23721266     4.0
11834421    39.0
5852959      6.0
            ...
15768785    37.0
10510466     8.0
18606040    41.0
23705045    48.0
23385277     6.0
Name: state_code, Length: 2486666, dtype: float64

In [171]:
race_mapping = {5: 'White', 3: 'Black or African American', 2: 'Asian', 1: 'American Indian or Alaska Native', 4: 'Native Hawaiian or Other Pacific Islander'}
hmda_sample['action_taken'] = hmda_sample['action_taken'].apply(lambda x: 1 if x in [1, 2] else 0)
hmda_sample['applicant_race_1'] = hmda_sample['applicant_race_1'].map(race_mapping)
hmda_sample.describe()

,as_of_year,action_taken,loan_type,loan_purpose,loan_amount_000s,msamd,county_code,applicant_ethnicity,co_applicant_ethnicity,co_applicant_race_1,...,applicant_income_000s,purchaser_type,rate_spread,hoepa_status,population,minority_population,hud_median_family_income,tract_to_msamd_income,number_of_owner_occupied_units,number_of_1_to_4_family_units
count,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,...,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06,2.486666e+06
mean,2.011078e+03,1.681597e-01,1.236123e+00,2.288440e+00,1.840260e+02,3.043349e+04,8.640120e+01,1.852879e+00,7.400962e-01,1.825391e+00,...,9.012557e+01,5.268335e-01,-2.136762e-01,1.999160e+00,5.556639e+03,3.366403e+01,6.697421e+04,1.074395e+02,1.447721e+03,1.885659e+03
std,3.375317e+00,3.740081e-01,5.249497e-01,8.884358e-01,3.617722e+02,1.125529e+04,1.007911e+02,3.542267e-01,9.375370e-01,2.328069e+00,...,1.513403e+02,1.841884e+00,1.947055e+00,2.897197e-02,2.765717e+03,2.909032e+01,1.374192e+04,3.908267e+01,8.098524e+02,9.754884e+02
min,2.007000e+03,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.014000e+04,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,...,1.000000e+00,0.000000e+00,-1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.440000e+04,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.008000e+03,0.000000e+00,1.000000e+00,1.000000e+00,7.300000e+01,1.974000e+04,2.900000e+01,2.000000e+00,0.000000e+00,0.000000e+00,...,4.100000e+01,0.000000e+00,-1.000000e+00,2.000000e+00,3.787000e+03,9.910000e+00,5.900000e+04,8.261000e+01,9.130000e+02,1.260000e+03
50%,2.011000e+03,0.000000e+00,1.000000e+00,3.000000e+00,1.390000e+02,3.154000e+04,6.300000e+01,2.000000e+00,0.000000e+00,0.000000e+00,...,6.500000e+01,0.000000e+00,-1.000000e+00,2.000000e+00,5.110000e+03,2.325000e+01,6.500000e+04,1.019400e+02,1.329000e+03,1.729000e+03
75%,2.014000e+03,0.000000e+00,1.000000e+00,3.000000e+00,2.370000e+02,4.014000e+04,1.090000e+02,2.000000e+00,2.000000e+00,5.000000e+00,...,1.020000e+02,0.000000e+00,-1.000000e+00,2.000000e+00,6.719000e+03,5.139000e+01,7.330000e+04,1.252200e+02,1.819000e+03,2.310000e+03
max,2.017000e+03,1.000000e+00,4.000000e+00,3.000000e+00,3.440000e+05,4.974000e+04,8.400000e+02,2.000000e+00,2.000000e+00,5.000000e+00,...,6.500000e+04,9.000000e+00,9.999000e+01,2.000000e+00,5.381200e+04,1.000000e+02,1.315000e+05,5.074700e+02,1.952900e+04,2.539100e+04

In [173]:
hmda_sample['applicant_race_1']

20493630                               White
785654                                 White
23721266                               White
11834421           Black or African American
5852959     American Indian or Alaska Native
                          ...
15768785           Black or African American
10510466                               White
18606040                               White
23705045                               White
23385277                               White
Name: applicant_race_1, Length: 2486666, dtype: object

In [272]:
race_state_dictionary = race_state_dict(hmda_sample, 'applicant_race_1', 'state_code')

In [429]:
Reversed_Race_Mapping = {'White': 5, 'Black or African American': 3, 'Asian': 2, 'American Indian or Alaska Native': 1, 'Native Hawaiian or Other Pacific Islander': 4}

In [431]:
hmda_sample['applicant_race_1'] = hmda_sample['applicant_race_1'].map(Reversed_Race_Mapping)

In [580]:
hmda_sample_no_rate_spread = hmda_sample.drop(columns=['rate_spread'])

In [874]:
hmda_remove_rate_spread = hmda.drop(columns=['rate_spread'])

In [1057]:
def by_state_samples_5(df, year_sample_size, remove_race=True):
    
    states = sorted(df['state_code'].unique())
    
    # Lists to store DataFrames for the "All Races" and "White" data for each state
    all_race_dfs = []  # Will store lists of DataFrames, each list corresponding to a state
    white_data_dfs = []  # Will store lists of DataFrames, each list corresponding to a state
    
    # Loop through each state
    for state in states:
        # Filter the dataframe for the current state
        state_data = df[df['state_code'] == state]

        sample_size = min(year_sample_size, len(state_data))

        # Sample the "White" race (assuming 'White' corresponds to value 5 in the ethnicity column)
        white_sample = value_sample(state_data, 'applicant_race_1', 5, sample_size)

        # Sample "All Races" (a random sample from the entire state's data, excluding specific race samples)
        all_sample = stratified_sample(state_data, 'applicant_race_1', sample_size)

        if remove_race:
            white_sample = white_sample.drop(columns=['co_applicant_race_1', 'applicant_race_1'])
            all_sample = all_sample.drop(columns=['co_applicant_race_1', 'applicant_race_1'])
        
        # # Add the state code to each sample to identify which state they belong to
        # white_sample['state_code'] = state
        # all_sample['state_code'] = state

        # Append to the lists
        all_race_dfs.append(all_sample)  
        white_data_dfs.append(white_sample) 
    
    return [all_race_dfs, white_data_dfs]

In [1059]:
state_sample5 = by_state_samples_5(hmda_remove_rate_spread, 1000)

In [1049]:
state_sample5

[[        index  as_of_year  action_taken  loan_type  loan_purpose  \
  0    24670037        2017             0          1             2
  1     6979983        2008             0          2             1
  2    12702138        2011             0          1             3
  3     3617120        2007             0          1             3
  4    17435252        2013             0          1             3
  ..        ...         ...           ...        ...           ...
  995  24589013        2017             0          1             3
  996  23029000        2016             1          1             1
  997  23175695        2016             0          2             3
  998  12532534        2011             0          2             1
  999   7101262        2008             0          1             1

       loan_amount_000s    msamd  state_code  county_code  applicant_ethnicity  \
  0                15.0  13820.0         1.0          9.0                    2
  1               177.0  13820.0         1.0         73.0                    1
  2               145.0  46220.0         1.0         63.0                    2
  3                15.0  26620.0         1.0         89.0                    2
  4               108.0  33860.0         1.0        101.0                    2
  ..                ...      ...         ...          ...                  ...
  995              13.0  19460.0         1.0         79.0                    2
  996             264.0  13820.0         1.0         73.0                    2
  997             102.0  23460.0         1.0         55.0                    2
  998              69.0  11500.0         1.0         15.0                    2
  999              78.0  19460.0         1.0        103.0                    2

       ...  co_applicant_sex  applicant_income_000s  purchaser_type  \
  0    ...                 0                   36.0               0
  1    ...                 2                   50.0               0
  2    ...                 0                   42.0               0
  3    ...                 0                   96.0               0
  4    ...                 2                  210.0               0
  ..   ...               ...                    ...             ...
  995  ...                 0                   17.0               0
  996  ...                 2                   62.0               7
  997  ...                 0                   62.0               0
  998  ...                 2                   32.0               0
  999  ...                 2                   44.0               0

       hoepa_status  population  minority_population  hud_median_family_income  \
  0               2      8775.0             2.750000                   61400.0
  1               2      6541.0             7.540000                   59100.0
  2               2      3123.0            83.089996                   55700.0
  3               2      5296.0            23.450001                   63800.0
  4               2      4933.0            62.150002                   61500.0
  ..            ...         ...                  ...                       ...
  995             2      4581.0            20.799999                   57700.0
  996             2     10433.0            12.720000                   62500.0
  997             2      4988.0             4.270000                   51200.0
  998             2      5539.0             6.320000                   51500.0
  999             2      8745.0             5.050000                   53100.0

       tract_to_msamd_income  number_of_owner_occupied_units  \
  0                80.800003                          2647.0
  1               110.570000                          2162.0
  2                56.169998                           984.0
  3               113.180000                           981.0
  4               115.980003                           823.0
  ..                     ...                             ...
  995             101.370003                          1792.0
  996             155.240005                          3367.0
  997             135.270004                          1544.0
  998             101.019997                          1815.0
  999              95.599998                          2890.0

       number_of_1_to_4_family_units
  0                           3477.0
  1                           2481.0
  2                           1731.0
  3                           1309.0
  4                           1119.0
  ..                             ...
  995                         2077.0
  996                         3716.0
  997                         1979.0
  998                         2321.0
  999                         3697.0

  [1000 rows x 22 columns],
          index  as_of_year  action_taken  loan_type  loan_purpose  \
  0    19479559        2015             0          1             2
  1    20403898        2015             0          3             1
  2    12203943        2011             0          1             3
  3    24365483        2017             0          3             3
  4    21291031        2016             0          1             3
  ..        ...         ...           ...        ...           ...
  995   8328104        2009             0          2             3
  996  24226485        2017             0          1             2
  997  20346046        2015             0          3             3
  998  10466168        2010             0          1             1
  999   5168923        2008             0          1             3

       loan_amount_000s    msamd  state_code  county_code  applicant_ethnicity  \
  0                12.0  11260.0         2.0        170.0                    2
  1               250.0  21820.0         2.0         90.0                    2
  2                69.0  11260.0         2.0        170.0                    2
  3               165.0  21820.0         2.0         90.0                    2
  4               260.0  11260.0         2.0         20.0                    2
  ..                ...      ...         ...          ...                  ...
  995             144.0  11260.0         2.0        170.0                    2
  996              30.0  11260.0         2.0         20.0                    2
  997             279.0  11260.0         2.0         20.0                    2
  998             227.0  11260.0         2.0         20.0                    2
  999             490.0  11260.0         2.0        170.0                    2

       ...  co_applicant_sex  applicant_income_000s  purchaser_type  \
  0    ...                 0                  120.0               0
  1    ...                 0                   77.0               0
  2    ...                 2                   88.0               0
  3    ...                 1                  112.0               0
  4    ...                 2                   71.0               0
  ..   ...               ...                    ...             ...
  995  ...                 1                   92.0               0
  996  ...                 0                  167.0               0
  997  ...                 0                   98.0               0
  998  ...                 2                  130.0               0
  999  ...                 2                   91.0               0

       hoepa_status  population  minority_population  hud_median_family_income  \
  0               2      4664.0            19.790001                   89600.0
  1               2     10052.0            18.400000                   85600.0
  2               2      1657.0            26.920000                   84000.0
  3               2      7632.0            18.990000                   84800.0
  4               2      5736.0            15.930000                   91000.0
  ..            ...         ...                  ...                       ...
  995             2      7160.0            13.810000                   80800.0
  996             2      4884.0            59.619999                   89400.0
  997             2     10549.0            17.510000                   89600.0
  998             2      5354.0            34.049999                   83600.0
  999             2      3765.0            18.490000                   77700.0

       tract_to_msamd_income  number_of_owner_occupied_units  \
  0               102.580002                          1052.0
  1               111.480003                          2590.0
  2                69.730003                           440.0
  3               100.879997                          1988.0
  4               133.779999                          1522.0
  ..                     ...                             ...
  995              96.839996                          2009.0
  996              65.510002                           918.0
  997             129.429993                          3080.0
  998              93.430000                          1375.0
  999              82.360001                           678.0

       number_of_1_to_4_family_units
  0                           1409.0
  1                           3225.0
  2                           1259.0
  3                           2975.0
  4                           1923.0
  ..                             ...
  995                         2664.0
  996                         1187.0
  997                         3541.0
  998                         1745.0
  999                         1274.0

  [1000 rows x 22 columns],
           index  as_of_year  action_taken  loan_type  loan_purpose  \
  0      2176555        2007             1          1             3
  1      5506975        2008             0          2             3
  2      8206051        2008             0          1             3
  3      3557062        2007             0          2             3
  4     19868428        2015             0          1             3
  ...        ...         ...           ...        ...           ...
  996   14420535        2012             0          1             3
  997   13954636        2012             0          2             1
  998   21075060        2015             0          1             2
  999   23842784        2017             0          1             3
  1000   2100135        2007             0          1             2

        loan_amount_000s    msamd  state_code  county_code  applicant_ethnicity  \
  0                204.0  38060.0         4.0         13.0                    2
  1                116.0  38060.0         4.0         13.0                    1
  2                150.0  38060.0         4.0         13.0                    2
  3                202.0  46060.0         4.0         19.0                    1
  4                 70.0  38060.0         4.0         21.0                    1
  ...                ...      ...         ...          ...                  ...
  996              180.0  38060.0         4.0         13.0                    2
  997              102.0  38060.0         4.0         21.0                    2
  998              180.0  46060.0         4.0         19.0                    2
  999              145.0  38060.0         4.0         13.0                    2
  1000              81.0  38060.0         4.0         13.0                    2

        ...  co_applicant_sex  applicant_income_000s  purchaser_type  \
  0     ...                 0                   36.0               0
  1     ...                 0                   46.0               0
  2     ...                 0                   29.0               0
  3     ...                 0                   33.0               0
  4     ...                 0                   55.0               0
  ...   ...               ...                    ...             ...
  996   ...                 0                   53.0               0
  997   ...                 2                   30.0               0
  998   ...                 2                   62.0               0
  999   ...                 0                   44.0               0
  1000  ...                 2                   57.0               0

        hoepa_status  population  minority_population  hud_median_family_income  \
  0                2      6152.0            14.950000                   59100.0
  1                2      5194.0            90.080002                   64200.0
  2                2      4720.0            58.330002                   64200.0
  3                2      4153.0            57.790001                   52400.0
  4                2      5230.0            24.299999                   64000.0
  ...            ...         ...                  ...                       ...
  996              2      2528.0             4.000000                   66400.0
  997              2     15769.0            33.080002                   66400.0
  998              2      3926.0            22.240000                   59000.0
  999              2      5723.0            32.759998                   66200.0
  1000             2      6483.0            24.660000                   59100.0

        tract_to_msamd_income  number_of_owner_occupied_units  \
  0                111.419998                          1939.0
  1                 65.599998                           892.0
  2                 78.430000                          1084.0
  3                 69.370003                          1248.0
  4                 76.339996                          1992.0
  ...                     ...                             ...
  996               88.580002                          1356.0
  997               96.709999                          2819.0
  998              129.850006                          1270.0
  999              113.290001                          1580.0
  1000             102.089996                          2049.0

        number_of_1_to_4_family_units
  0                            2216.0
  1                            1201.0
  2                            1237.0
  3                            1865.0
  4                            3150.0
  ...                             ...
  996                          1766.0
  997                          3953.0
  998                          1634.0
  999                          2005.0
  1000                         2420.0

  [1001 rows x 22 columns],
           index  as_of_year  action_taken  loan_type  loan_purpose  \
  0     20887800        2015             0          3             3
  1     18548706        2014             0          2             3
  2     20696863        2015             0          1             2
  3     17601813        2013             1          1             3
  4     18470178        2014             0          3             1
  ...        ...         ...           ...        ...           ...
  996   10348728        2009             1          1             3
  997    5027026        2007             0          1             3
  998    4348192        2007             1          1             1
  999    4996689        2007             0          1             3
  1000  11815182        2010             1          1             1

        loan_amount_000s    msamd  state_code  county_code  applicant_ethnicity  \
  0                 32.0  22220.0         5.0          7.0                    2
  1                 57.0  22900.0         5.0         33.0                    2
  2                 69.0  22220.0         5.0          7.0                    2
  3                134.0  22220.0         5.0          7.0                    2
  4                111.0  22220.0         5.0          7.0                    2
  ...                ...      ...         ...          ...                  ...
  996               52.0  22900.0         5.0         33.0                    2
  997              160.0  22220.0         5.0          7.0                    2
  998               72.0  22220.0         5.0        143.0                    2
  999               34.0  22220.0         5.0          7.0                    1
  1000             334.0  22220.0         5.0          7.0                    2

        ...  co_applicant_sex  applicant_income_000s  purchaser_type  \
  0     ...                 2                   19.0               0
  1     ...                 0                   13.0               0
  2     ...                 0                   26.0               0
  3     ...                 0                   60.0               0
  4     ...                 0                   44.0               0
  ...   ...               ...                    ...             ...
  996   ...                 0                   47.0               0
  997   ...                 2                   30.0               0
  998   ...                 0                   90.0               8
  999   ...                 2                   63.0               0
  1000  ...                 1                  208.0               0

        hoepa_status  population  minority_population  hud_median_family_income  \
  0                2      4551.0            35.970001                   58700.0
  1                2      5956.0             5.660000                   49900.0
  2                2      6947.0            24.559999                   58700.0
  3                2      6415.0            23.959999                   56700.0
  4                2      6518.0            20.240000                   59500.0
  ...            ...         ...                  ...                       ...
  996              2      3976.0             4.800000                   46500.0
  997              2      7453.0             9.940000                   53100.0
  998              2      4383.0             4.810000                   53100.0
  999              2      9922.0            29.280001                   53100.0
  1000             2      5052.0             8.120000                   55000.0

        tract_to_msamd_income  number_of_owner_occupied_units  \
  0                 60.709999                           853.0
  1                103.970001                          1690.0
  2                103.919998                          1659.0
  3                112.529999                          1569.0
  4                 87.750000                          1646.0
  ...                     ...                             ...
  996               97.750000                          1208.0
  997              117.940002                          2386.0
  998               97.080002                          1288.0
  999              106.599998                          2448.0
  1000             101.199997                          1699.0

        number_of_1_to_4_family_units
  0                            1677.0
  1                            2359.0
  2                            2630.0
  3                            2556.0
  4                            2334.0
  ...                             ...
  996                          1646.0
  997                          3087.0
  998                          1758.0
  999                          3615.0
  1000                         2667.0

  [1001 rows x 22 columns],
          index  as_of_year  action_taken  loan_type  loan_purpose  \
  0      265188        2007             1          1             3
  1    13025778        2011             0          1             3
  2     3137395        2007             0          1             3
  3     8676937        2009             0          1             3
  4     3546855        2007             0          1             3
  ..        ...         ...           ...        ...           ...
  994  23773212        2017             0          1             3
  995   9240704        2009             0          2             3
  996  22446865        2016             0          1             1
  997   9201907        2009             0          2             3
  998  21498690        2016             0          1             3

       loan_amount_000s    msamd  state_code  county_code  applicant_ethnicity  \

In [979]:
len(state_sample5)

2

In [1075]:
def model_testing5(model, sample_data, y_col, cv=5, param_grid = None):

    race_strings = ['American Indian', 'Asian', 'Black', 'Hawaiian/Other', 'White']
    # List to store results for each state and dataset
    all_results = []  

    # Set up Stratified K-Fold cross-validation
    stratified_kfold = StratifiedKFold(n_splits=cv, shuffle=True, random_state=313)

    # Define scoring metrics
    scoring = {'roc_auc': 'roc_auc', 'precision': 'precision', 'recall': 'recall', 'accuracy': 'accuracy'}

    # Loop through each state
    models = []
    race = []
    state = []
    accuracy = []
    precision = []
    recall = []
    roc_auc = []
    confusion_mats = []
    i = 0
    for i in range(len(sample_data[1])):

        stratified_kfold = StratifiedKFold(n_splits=cv, shuffle=True, random_state=313)
        
        # Split the data into features (X) and target (y) for both datasets
        X_all_race, y_all_race = split_xy(sample_data[0][i], y_col)
        X_white, y_white = split_xy(sample_data[1][i], y_col)

        # Initialize GridSearchCV for "All Races" model
        all_race_search = GridSearchCV(model, param_grid, scoring=scoring, cv=stratified_kfold, refit='roc_auc', return_train_score=True)
        all_race_search.fit(X_all_race, y_all_race)
        
        # Initialize GridSearchCV for "White" model
        white_search = GridSearchCV(model, param_grid, scoring=scoring, cv=stratified_kfold, refit='roc_auc', return_train_score=True)
        white_search.fit(X_white, y_white)

          # Predict the test data for each race

        for j in range(0, 5):
            X_test, y_test = split_xy(sample_data[2][j], y_col)
            white_preds = white_search.predict(X_test)
            white_results = classification_report(y_test, white_preds, output_dict=True)
            all_race_preds = all_race_search.predict(X_test)
            all_race_results = classification_report(y_test, all_race_preds, output_dict=True)
            # Add results to thier respective lists
            models.append('White Only')
            models.append('All Races')
            race.append(race_strings[j])
            race.append(race_strings[j])
            state.append(sample_data[0][i]['state_code'])
            state.append(sample_data[1][i]['state_code'])
            accuracy.append(white_results['accuracy'])
            accuracy.append(all_race_results['accuracy'])
            precision.append(white_results['1']['precision'])
            precision.append(all_race_results['1']['precision'])
            recall.append(white_results['1']['recall'])
            recall.append(all_race_results['1']['recall'])
            roc_auc.append(white_results['1']['f1-score'])
            roc_auc.append(all_race_results['1']['f1-score'])
            # Add confusion matrices values to list
            confusion_mats.append(confusion_matrix(y_test, white_preds))
            confusion_mats.append(confusion_matrix(y_test, all_race_preds))
        
    return pd.DataFrame({'Model': models, 'Race': race, 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'ROC-AUC': roc_auc, 'Confusion Matrix': confusion_mats, 'State': state })
        
    #     # Add model type and state to results
    #     all_race_results['Model'] = 'All Races'
    #     white_results['Model'] = 'White only'
    #     all_race_results['state_code'] = state_data_all_race['state_code']
    #     white_results['state_code'] = state_data_white['state_code']
        
    #     # Combine results for both models into a single DataFrame
    #     combined_results = pd.concat([all_race_results, white_results])

    #     # Select relevant columns and rename for clarity
    #     relevant_columns = [f'param_{param}' for param in param_grid.keys()] + [
    #         'mean_test_roc_auc', 'mean_test_precision', 'mean_test_recall', 'mean_test_accuracy', 'State', 'Model']
    #     combined_results = combined_results[relevant_columns]

    #     # Rename columns for final output
    #     column_mapping = {f'param_{param}': param for param in param_grid.keys()}
    #     column_mapping.update({
    #         'mean_test_roc_auc': 'ROC-AUC Score',
    #         'mean_test_precision': 'Precision',
    #         'mean_test_recall': 'Recall',
    #         'mean_test_accuracy': 'Accuracy'})
    #     combined_results.rename(columns=column_mapping, inplace=True)

    #     # Order the columns so that Model and State come first
    #     column_order = ['State', 'Model'] + [param for param in param_grid.keys()] + ['ROC-AUC Score', 'Precision', 'Recall', 'Accuracy']
    #     combined_results = combined_results[column_order]

    #     # Append results for the current state to the all_results list
    #     all_results.append(combined_results)
    
    # # Concatenate all results into a single DataFrame
    # final_results = pd.concat(all_results, ignore_index=True)
    
    # return final_results

In [1038]:
state_sample5

[[[        index  as_of_year  action_taken  loan_type  loan_purpose  \
   0    24670037        2017             0          1             2
   1     6979983        2008             0          2             1
   2    12702138        2011             0          1             3
   3     3617120        2007             0          1             3
   4    17435252        2013             0          1             3
   ..        ...         ...           ...        ...           ...
   995  24589013        2017             0          1             3
   996  23029000        2016             1          1             1
   997  23175695        2016             0          2             3
   998  12532534        2011             0          2             1
   999   7101262        2008             0          1             1

        loan_amount_000s    msamd  state_code  county_code  applicant_ethnicity  \
   0                15.0  13820.0         1.0          9.0                    2
   1               177.0  13820.0         1.0         73.0                    1
   2               145.0  46220.0         1.0         63.0                    2
   3                15.0  26620.0         1.0         89.0                    2
   4               108.0  33860.0         1.0        101.0                    2
   ..                ...      ...         ...          ...                  ...
   995              13.0  19460.0         1.0         79.0                    2
   996             264.0  13820.0         1.0         73.0                    2
   997             102.0  23460.0         1.0         55.0                    2
   998              69.0  11500.0         1.0         15.0                    2
   999              78.0  19460.0         1.0        103.0                    2

        ...  co_applicant_sex  applicant_income_000s  purchaser_type  \
   0    ...                 0                   36.0               0
   1    ...                 2                   50.0               0
   2    ...                 0                   42.0               0
   3    ...                 0                   96.0               0
   4    ...                 2                  210.0               0
   ..   ...               ...                    ...             ...
   995  ...                 0                   17.0               0
   996  ...                 2                   62.0               7
   997  ...                 0                   62.0               0
   998  ...                 2                   32.0               0
   999  ...                 2                   44.0               0

        hoepa_status  population  minority_population  hud_median_family_income  \
   0               2      8775.0             2.750000                   61400.0
   1               2      6541.0             7.540000                   59100.0
   2               2      3123.0            83.089996                   55700.0
   3               2      5296.0            23.450001                   63800.0
   4               2      4933.0            62.150002                   61500.0
   ..            ...         ...                  ...                       ...
   995             2      4581.0            20.799999                   57700.0
   996             2     10433.0            12.720000                   62500.0
   997             2      4988.0             4.270000                   51200.0
   998             2      5539.0             6.320000                   51500.0
   999             2      8745.0             5.050000                   53100.0

        tract_to_msamd_income  number_of_owner_occupied_units  \
   0                80.800003                          2647.0
   1               110.570000                          2162.0
   2                56.169998                           984.0
   3               113.180000                           981.0
   4               115.980003                           823.0
   ..                     ...                             ...
   995             101.370003                          1792.0
   996             155.240005                          3367.0
   997             135.270004                          1544.0
   998             101.019997                          1815.0
   999              95.599998                          2890.0

        number_of_1_to_4_family_units
   0                           3477.0
   1                           2481.0
   2                           1731.0
   3                           1309.0
   4                           1119.0
   ..                             ...
   995                         2077.0
   996                         3716.0
   997                         1979.0
   998                         2321.0
   999                         3697.0

   [1000 rows x 22 columns]],
  [        index  as_of_year  action_taken  loan_type  loan_purpose  \
   0    19479559        2015             0          1             2
   1    20403898        2015             0          3             1
   2    12203943        2011             0          1             3
   3    24365483        2017             0          3             3
   4    21291031        2016             0          1             3
   ..        ...         ...           ...        ...           ...
   995   8328104        2009             0          2             3
   996  24226485        2017             0          1             2
   997  20346046        2015             0          3             3
   998  10466168        2010             0          1             1
   999   5168923        2008             0          1             3

        loan_amount_000s    msamd  state_code  county_code  applicant_ethnicity  \
   0                12.0  11260.0         2.0        170.0                    2
   1               250.0  21820.0         2.0         90.0                    2
   2                69.0  11260.0         2.0        170.0                    2
   3               165.0  21820.0         2.0         90.0                    2
   4               260.0  11260.0         2.0         20.0                    2
   ..                ...      ...         ...          ...                  ...
   995             144.0  11260.0         2.0        170.0                    2
   996              30.0  11260.0         2.0         20.0                    2
   997             279.0  11260.0         2.0         20.0                    2
   998             227.0  11260.0         2.0         20.0                    2
   999             490.0  11260.0         2.0        170.0                    2

        ...  co_applicant_sex  applicant_income_000s  purchaser_type  \
   0    ...                 0                  120.0               0
   1    ...                 0                   77.0               0
   2    ...                 2                   88.0               0
   3    ...                 1                  112.0               0
   4    ...                 2                   71.0               0
   ..   ...               ...                    ...             ...
   995  ...                 1                   92.0               0
   996  ...                 0                  167.0               0
   997  ...                 0                   98.0               0
   998  ...                 2                  130.0               0
   999  ...                 2                   91.0               0

        hoepa_status  population  minority_population  hud_median_family_income  \
   0               2      4664.0            19.790001                   89600.0
   1               2     10052.0            18.400000                   85600.0
   2               2      1657.0            26.920000                   84000.0
   3               2      7632.0            18.990000                   84800.0
   4               2      5736.0            15.930000                   91000.0
   ..            ...         ...                  ...                       ...
   995             2      7160.0            13.810000                   80800.0
   996             2      4884.0            59.619999                   89400.0
   997             2     10549.0            17.510000                   89600.0
   998             2      5354.0            34.049999                   83600.0
   999             2      3765.0            18.490000                   77700.0

        tract_to_msamd_income  number_of_owner_occupied_units  \
   0               102.580002                          1052.0
   1               111.480003                          2590.0
   2                69.730003                           440.0
   3               100.879997                          1988.0
   4               133.779999                          1522.0
   ..                     ...                             ...
   995              96.839996                          2009.0
   996              65.510002                           918.0
   997             129.429993                          3080.0
   998              93.430000                          1375.0
   999              82.360001                           678.0

        number_of_1_to_4_family_units
   0                           1409.0
   1                           3225.0
   2                           1259.0
   3                           2975.0
   4                           1923.0
   ..                             ...
   995                         2664.0
   996                         1187.0
   997                         3541.0
   998                         1745.0
   999                         1274.0

   [1000 rows x 22 columns]],
  [         index  as_of_year  action_taken  loan_type  loan_purpose  \
   0      2176555        2007             1          1             3
   1      5506975        2008             0          2             3
   2      8206051        2008             0          1             3
   3      3557062        2007             0          2             3
   4     19868428        2015             0          1             3
   ...        ...         ...           ...        ...           ...
   996   14420535        2012             0          1             3
   997   13954636        2012             0          2             1
   998   21075060        2015             0          1             2
   999   23842784        2017             0          1             3
   1000   2100135        2007             0          1             2

         loan_amount_000s    msamd  state_code  county_code  applicant_ethnicity  \
   0                204.0  38060.0         4.0         13.0                    2
   1                116.0  38060.0         4.0         13.0                    1
   2                150.0  38060.0         4.0         13.0                    2
   3                202.0  46060.0         4.0         19.0                    1
   4                 70.0  38060.0         4.0         21.0                    1
   ...                ...      ...         ...          ...                  ...
   996              180.0  38060.0         4.0         13.0                    2
   997              102.0  38060.0         4.0         21.0                    2
   998              180.0  46060.0         4.0         19.0                    2
   999              145.0  38060.0         4.0         13.0                    2
   1000              81.0  38060.0         4.0         13.0                    2

         ...  co_applicant_sex  applicant_income_000s  purchaser_type  \
   0     ...                 0                   36.0               0
   1     ...                 0                   46.0               0
   2     ...                 0                   29.0               0
   3     ...                 0                   33.0               0
   4     ...                 0                   55.0               0
   ...   ...               ...                    ...             ...
   996   ...                 0                   53.0               0
   997   ...                 2                   30.0               0
   998   ...                 2                   62.0               0
   999   ...                 0                   44.0               0
   1000  ...                 2                   57.0               0

         hoepa_status  population  minority_population  hud_median_family_income  \
   0                2      6152.0            14.950000                   59100.0
   1                2      5194.0            90.080002                   64200.0
   2                2      4720.0            58.330002                   64200.0
   3                2      4153.0            57.790001                   52400.0
   4                2      5230.0            24.299999                   64000.0
   ...            ...         ...                  ...                       ...
   996              2      2528.0             4.000000                   66400.0
   997              2     15769.0            33.080002                   66400.0
   998              2      3926.0            22.240000                   59000.0
   999              2      5723.0            32.759998                   66200.0
   1000             2      6483.0            24.660000                   59100.0

         tract_to_msamd_income  number_of_owner_occupied_units  \
   0                111.419998                          1939.0
   1                 65.599998                           892.0
   2                 78.430000                          1084.0
   3                 69.370003                          1248.0
   4                 76.339996                          1992.0
   ...                     ...                             ...
   996               88.580002                          1356.0
   997               96.709999                          2819.0
   998              129.850006                          1270.0
   999              113.290001                          1580.0
   1000             102.089996                          2049.0

         number_of_1_to_4_family_units
   0                            2216.0
   1                            1201.0
   2                            1237.0
   3                            1865.0
   4                            3150.0
   ...                             ...
   996                          1766.0
   997                          3953.0
   998                          1634.0
   999                          2005.0
   1000                         2420.0

   [1001 rows x 22 columns]],
  [         index  as_of_year  action_taken  loan_type  loan_purpose  \
   0     20887800        2015             0          3             3
   1     18548706        2014             0          2             3
   2     20696863        2015             0          1             2
   3     17601813        2013             1          1             3
   4     18470178        2014             0          3             1
   ...        ...         ...           ...        ...           ...
   996   10348728        2009             1          1             3
   997    5027026        2007             0          1             3
   998    4348192        2007             1          1             1
   999    4996689        2007             0          1             3
   1000  11815182        2010             1          1             1

         loan_amount_000s    msamd  state_code  county_code  applicant_ethnicity  \
   0                 32.0  22220.0         5.0          7.0                    2
   1                 57.0  22900.0         5.0         33.0                    2
   2                 69.0  22220.0         5.0          7.0                    2
   3                134.0  22220.0         5.0          7.0                    2
   4                111.0  22220.0         5.0          7.0                    2
   ...                ...      ...         ...          ...                  ...
   996               52.0  22900.0         5.0         33.0                    2
   997              160.0  22220.0         5.0          7.0                    2
   998               72.0  22220.0         5.0        143.0                    2
   999               34.0  22220.0         5.0          7.0                    1
   1000             334.0  22220.0         5.0          7.0                    2

         ...  co_applicant_sex  applicant_income_000s  purchaser_type  \
   0     ...                 2                   19.0               0
   1     ...                 0                   13.0               0
   2     ...                 0                   26.0               0
   3     ...                 0                   60.0               0
   4     ...                 0                   44.0               0
   ...   ...               ...                    ...             ...
   996   ...                 0                   47.0               0
   997   ...                 2                   30.0               0
   998   ...                 0                   90.0               8
   999   ...                 2                   63.0               0
   1000  ...                 1                  208.0               0

         hoepa_status  population  minority_population  hud_median_family_income  \
   0                2      4551.0            35.970001                   58700.0
   1                2      5956.0             5.660000                   49900.0
   2                2      6947.0            24.559999                   58700.0
   3                2      6415.0            23.959999                   56700.0
   4                2      6518.0            20.240000                   59500.0
   ...            ...         ...                  ...                       ...
   996              2      3976.0             4.800000                   46500.0
   997              2      7453.0             9.940000                   53100.0
   998              2      4383.0             4.810000                   53100.0
   999              2      9922.0            29.280001                   53100.0
   1000             2      5052.0             8.120000                   55000.0

         tract_to_msamd_income  number_of_owner_occupied_units  \
   0                 60.709999                           853.0
   1                103.970001                          1690.0
   2                103.919998                          1659.0
   3                112.529999                          1569.0
   4                 87.750000                          1646.0
   ...                     ...                             ...
   996               97.750000                          1208.0
   997              117.940002                          2386.0
   998               97.080002                          1288.0
   999              106.599998                          2448.0
   1000             101.199997                          1699.0

         number_of_1_to_4_family_units
   0                            1677.0
   1                            2359.0
   2                            2630.0
   3                            2556.0
   4                            2334.0
   ...                             ...
   996                          1646.0
   997                          3087.0
   998                          1758.0
   999                          3615.0
   1000                         2667.0

   [1001 rows x 22 columns]],
  [        index  as_of_year  action_taken  loan_type  loan_purpose  \
   0      265188        2007             1          1             3
   1    13025778        2011             0          1             3
   2     3137395        2007             0          1             3
   3     8676937        2009             0          1             3
   4     3546855        2007             0          1             3
   ..        ...         ...           ...        ...           ...
   994  23773212        2017             0          1             3

In [1077]:
(state_sample5.append(samples[2]))
state_sample5
model_testing5(rforest, state_sample5, 'action_taken', param_grid={'max_depth': [3, 5], 'bootstrap': [True], 'max_samples':[100, 200]}, cv=5)

C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Ariana Timbol\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

,Model,Race,Accuracy,Precision,Recall,ROC-AUC,Confusion Matrix,State
0,White Only,American Indian,0.950909,1.000000,0.465347,0.635135,"[[1998, 0], [108, 94]]",0 1.0 1 1.0 2 1.0 3 1.0 4 ...
1,All Races,American Indian,0.951364,1.000000,0.470297,0.639731,"[[1998, 0], [107, 95]]",9660459 1.0 23084669 1.0 7075930 1....
2,White Only,Asian,0.965000,1.000000,0.594737,0.745875,"[[2010, 0], [77, 113]]",0 1.0 1 1.0 2 1.0 3 1.0 4 ...
3,All Races,Asian,0.965455,1.000000,0.600000,0.750000,"[[2010, 0], [76, 114]]",9660459 1.0 23084669 1.0 7075930 1....
4,White Only,Black,0.953182,1.000000,0.679128,0.808905,"[[1879, 0], [103, 218]]",0 1.0 1 1.0 2 1.0 3 1.0 4 ...
...,...,...,...,...,...,...,...,...
515,All Races,Black,0.945909,0.990291,0.635514,0.774194,"[[1877, 2], [117, 204]]",11957424 72.0 5868488 72.0 21182885 ...
516,White Only,Hawaiian/Other,0.950455,0.834356,0.623853,0.713911,"[[1955, 27], [82, 136]]",0 72.0 1 72.0 2 72.0 3 72....
517,All Races,Hawaiian/Other,0.954091,0.939850,0.573394,0.712251,"[[1974, 8], [93, 125]]",11957424 72.0 5868488 72.0 21182885 ...
518,White Only,White,0.918182,0.930876,0.550409,0.691781,"[[1818, 15], [165, 202]]",0 72.0 1 72.0 2 72.0 3 72....
519,All Races,White,0.918636,0.960784,0.534060,0.686515,"[[1825, 8], [171, 196]]",11957424 72.0 5868488 72.0 21182885 ...

In [897]:
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

def race_tests5(model, sample_data, y_col, cv=5, param_grid=None):
    """Function that tests each race sample against the specified model.
    The y_col is the target column name.
    
    - pd.DataFrame: Contains the performance metrics for each race and model
    """
    
    # Race categories to label the race column
    race_strings = ['American Indian', 'Asian', 'Black', 'Hawaiian/Other', 'White']
    
    # Create the white model dataset (White only)
    X_white, y_white = split_xy(sample_data[1], y_col)
    
    # Create the all race model dataset (All Races combined)
    X_all, y_all = split_xy(sample_data[0], y_col)

    # Set up Stratified K-Fold cross-validation
    stratified_kfold = StratifiedKFold(n_splits=cv, shuffle=True, random_state=313)

    # Initialize GridSearchCV for White Only Model
    white_search = GridSearchCV(model, param_grid=param_grid, cv=stratified_kfold)
    white_model = white_search.fit(X_white, y_white)
    
    # Initialize GridSearchCV for All Races Model
    all_search = GridSearchCV(model, param_grid=param_grid, cv=stratified_kfold)
    all_race_model = all_search.fit(X_all, y_all)

    # Store results for each race
    models = []
    race = []
    accuracy = []
    precision = []
    recall = []
    roc_auc = []
    confusion_mats = []

    # Loop through race categories (1 to 5) for testing
    for i in range(0, 5):
        # Get the current race data (from race_tests_df)
        X_test, y_test = split_xy(sample_data[2], y_col)
        
        # Get predictions for White Only Model
        white_preds = white_model.predict(X_test)
        white_results = classification_report(y_test, white_preds, output_dict=True)
        
        # Get predictions for All Races Model
        all_race_preds = all_race_model.predict(X_test)
        all_race_results = classification_report(y_test, all_race_preds, output_dict=True)
        
        # Add results to their respective lists
        models.append('White Only')
        models.append('All Races')
        
        race.append(race_strings[i])
        race.append(race_strings[i])
        
        accuracy.append(white_results['accuracy'])
        accuracy.append(all_race_results['accuracy'])
        
        precision.append(white_results['1']['precision'])
        precision.append(all_race_results['1']['precision'])
        
        recall.append(white_results['1']['recall'])
        recall.append(all_race_results['1']['recall'])
        
        roc_auc.append(white_results['1']['f1-score'])
        roc_auc.append(all_race_results['1']['f1-score'])
        
        # Add confusion matrix values to list
        confusion_mats.append(confusion_matrix(y_test, white_preds))
        confusion_mats.append(confusion_matrix(y_test, all_race_preds))

    # Create a DataFrame to summarize the results
    results_df = pd.DataFrame({
        'Model': models,
        'Race': race,
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'ROC-AUC': roc_auc,
        'Confusion Matrix': confusion_mats
    })

    return results_df

In [ ]:
logit = Pipeline([
    ('scaler', StandardScaler()),  
    ('logit', LogisticRegression(random_state=313))
])

model_testing5(logit, state_sample5, 'action_taken', param_grid={'logit__penalty': ['l2'],
             'logit__C': [0.1, 1, 10, 100], 'logit__max_iter':[100, 200]}, cv=5)

In [655]:
model_testing_state(rforest, state_sample5, 'action_taken', param_grid={'max_depth': [3, 5], 'bootstrap': [True], 'max_samples':[100, 500]}, cv=5)

KeyError: 0

In [836]:
hmda.dtypes

as_of_year                          int64
action_taken                        int64
loan_type                           int64
loan_purpose                        int64
loan_amount_000s                  float64
msamd                             float64
state_code                        float64
county_code                       float64
applicant_ethnicity                 int64
co_applicant_ethnicity              int64
applicant_race_1                    int64
co_applicant_race_1                 int64
applicant_sex                       int64
co_applicant_sex                    int64
applicant_income_000s             float64
purchaser_type                      int64
rate_spread                       float64
hoepa_status                        int64
population                        float64
minority_population               float64
hud_median_family_income          float64
tract_to_msamd_income             float64
number_of_owner_occupied_units    float64
number_of_1_to_4_family_units     float64
dtype: object

In [ ]:
logit = LogisticRegression(random_state=313)
rforest = RandomForestClassifier(random_state=313)

model_testing(rforest, state_samples, 'action_taken', param_grid={'max_depth': [3, 5], 'bootstrap': [True], 'max_samples':[100, 500]}, cv=5)

In [ ]:
race_tests(RandomForestClassifier(random_state=313), state_samples, 'action_taken', param_grid={'max_depth': [5], 'bootstrap': [True], 'max_samples':[500]})